apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-ca
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: ca-bundle
spec:
  # Gera o CA interno do cluster; Secret referenciado pelo ca-issuer.
  isCA: true
  commonName: lab-ca.homelab.local
  secretName: lab-ca-bundle

  # 10 anos
  duration: 87600h
  renewBefore: 720h  # 30 dias

  # ECDSA P-256
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always

  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
